cache:
	g++ cache.cpp -o cache_simulate

inclusive:
	g++ inclusive.cpp -o cache_simulate

tr1:
	./cache_simulate 64 1024 2 65536 8 ./memory_trace_files/trace1.txt

tr2:
	./cache_simulate 64 1024 2 65536 8 ./memory_trace_files/trace2.txt

tr3:
	./cache_simulate 64 1024 2 65536 8 ./memory_trace_files/trace3.txt

tr4:
	./cache_simulate 64 1024 2 65536 8 ./memory_trace_files/trace4.txt

tr5:
	./cache_simulate 64 1024 2 65536 8 ./memory_trace_files/trace5.txt

tr6:
	./cache_simulate 64 1024 2 65536 8 ./memory_trace_files/trace6.txt

tr7:
	./cache_simulate 64 1024 2 65536 8 ./memory_trace_files/trace7.txt

tr8:
	./cache_simulate 64 1024 2 65536 8 ./memory_trace_files/trace8.txt

clean:
	rm -f cache_simulate